### ISSUE TITLE
README example should use activations

### ISSUE THREAD

**Issue by ofzeng** [SurrealAI/TorchX#4]
My understanding is that the torchx L.Linear layers do not have an implicit activation after them.  If that is the case, to avoid confusion we should have L.ReLU() layers in the example as well.

```xp = L.Conv2d(10, kernel_size=5, stride=2)(xp_input)
branch1 = L.Conv2d(30, kernel_size=7, padding=2)(xp)  # no need to specify input channel
branch2 = L.Conv2d(30, kernel_size=5, padding=1)(xp)
xp = branch1 * branch2
xp = xp.flatten()
xp = L.Linear(80)(xp)  # no need to calculate the flattened shape
############## TODO: is there a relu here?
xp = L.Linear(10)(xp)```

**Comment by LinxiFan** [comment]
I just added a line "omitting nonlinearity for simplicity" in README. Thanks for the report
