### ISSUE TITLE
comparison vs torch built in sequential

### ISSUE THREAD

**Issue by ahundt** [SurrealAI/TorchX#6]
How does torchX compare to the pytorch 1.0 sequential models and containers?

https://pytorch.org/docs/master/nn.html?highlight=sequential#torch.nn.Sequential
https://github.com/torch/nn/blob/master/doc/containers.md

**Comment by LinxiFan** [comment]
TorchX infers the shape automatically. PyTorch 1.0 and 0.4 are the same on this part: you have to manually specify the input shape, while it's in fact redundant. This becomes particularly annoying for the flatten layer after conv.

**Comment by ahundt** [comment]
Ah yes I see, and their new version still does not fix it, that is annoying! Thanks!
